# netlify.toml

[[redirects]]
  from = "/proxy/*"
  to = "https://app.assignr.com/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/api/*"
  to = "https://api.assignr.com/api/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }
  